name = "DragonHome"
author = "Trapolis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce9d856afe67689b833812ad453253db7a64416b143d5121647b121db18542b1"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
