name = "DragonHome"
author = "Trapolis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ead786ae72c0df1bc387fe1dc6fea60b269a7863677b9190da965c4b14ab44c"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
