name = "DragonHome"
author = "Trapolis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2b05c408419c9b1387ab7fb9b1adcd8702df6219bcf30dc3f9d30d8ae25ec0c"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
