name = "DragonHome"
author = "Trapolis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1fe10cddb43b7bea61e99135beedf31432c2d2021b6bbbc97310f9a2a9caca4"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
