name = "DragonHome"
author = "Trapolis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a2fc56db0bf2ddee0a289f294fee19ba3ee7a35b4a3302d9272d1e61a4f4ba9"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
