name = "DragonHome"
author = "Trapolis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc31f82d37785b5285a50048ef674387d6bb3ac28b7a9847aa1fa5fbcabeb0fb"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
