name = "DragonHome"
author = "Trapolis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "378e657f5e52d7c3968934f0c00515b7396d4856f59cbdd1fbaf432b74d66923"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
