name = "DragonHome"
author = "Trapolis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c4f692cc827d784479336e69854a2b32f4cefaf551bf6805380662e19078149"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
