name = "DragonHome"
author = "Trapolis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca45a92da818d2b5ce49af1fa8f43636bd142724d25e07a1c062fd2d8bf321df"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
